# Generated by Django 4.2.30 on 2026-07-09 05:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.CharField(max_length=64, unique=True)),
                ('account_login', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to='db.workspace')),
            ],
            options={
                'verbose_name': 'GitHub Installation',
                'verbose_name_plural': 'GitHub Installations',
                'db_table': 'github_ext_installations',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('delivery_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='received', max_length=32)),
                ('headers', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'GitHub Webhook Delivery',
                'verbose_name_plural': 'GitHub Webhook Deliveries',
                'db_table': 'github_ext_webhook_deliveries',
            },
        ),
        migrations.CreateModel(
            name='StateTransitionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('project', 'Project')], default='global', max_length=16)),
                ('rules', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_state_transition_configs', to='db.project')),
            ],
            options={
                'verbose_name': 'GitHub State Transition Config',
                'verbose_name_plural': 'GitHub State Transition Configs',
                'db_table': 'github_ext_state_transition_configs',
            },
        ),
        migrations.CreateModel(
            name='WorkItemGithubLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('branch', 'Branch'), ('pr', 'Pull Request'), ('commit', 'Commit'), ('issue', 'Issue')], max_length=16)),
                ('external_id', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_links', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_links', to='db.project')),
            ],
            options={
                'verbose_name': 'Work Item GitHub Link',
                'verbose_name_plural': 'Work Item GitHub Links',
                'db_table': 'github_ext_work_item_links',
                'unique_together': {('issue', 'link_type', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='RepoProjectMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repo_full_name', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_project_maps', to='github_ext.githubinstallation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_repo_maps', to='db.project')),
            ],
            options={
                'verbose_name': 'GitHub Repo Project Map',
                'verbose_name_plural': 'GitHub Repo Project Maps',
                'db_table': 'github_ext_repo_project_maps',
                'unique_together': {('installation', 'repo_full_name')},
            },
        ),
    ]
