# Generated by Django 4.2.30 on 2026-06-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_migrate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migrationrun',
            options={'ordering': ('-created_at',), 'verbose_name': 'Migration Run', 'verbose_name_plural': 'Migration Runs'},
        ),
        migrations.RenameIndex(
            model_name='migrationrecord',
            new_name='clickup_mig_run_id_11f103_idx',
            old_name='cm_record_run_status_idx',
        ),
        migrations.RenameIndex(
            model_name='migrationrecord',
            new_name='clickup_mig_source__8ae9ca_idx',
            old_name='cm_record_src_idx',
        ),
        migrations.AlterField(
            model_name='clickupcustomfieldarchive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clickupcustomfieldarchive',
            name='issue_external_id',
            field=models.CharField(help_text='ClickUp task id', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='clickupcustomfieldarchive',
            name='raw_json',
            field=models.JSONField(help_text='Raw custom_fields array from ClickUp'),
        ),
        migrations.AlterField(
            model_name='clickupcustomfieldarchive',
            name='raw_markdown',
            field=models.TextField(blank=True, help_text='Rendered Markdown table appended to description'),
        ),
        migrations.AlterField(
            model_name='emailcoverage',
            name='clickup_email',
            field=models.EmailField(help_text='Email from ClickUp member', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailcoverage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailcoverage',
            name='plane_user_id',
            field=models.CharField(blank=True, help_text='Plane User.id (UUID string) or null for bot fallback', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailcoverage',
            name='signed_off',
            field=models.BooleanField(db_index=True, default=False, help_text='Operator has signed off on this mapping (required before --apply)'),
        ),
        migrations.AlterField(
            model_name='mappingtable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mappingtable',
            name='source_key',
            field=models.TextField(help_text='JSON-encoded source identifier'),
        ),
        migrations.AlterField(
            model_name='mappingtable',
            name='source_meta',
            field=models.JSONField(default=dict, help_text='Extra context for the reviewer (color, count, etc.)'),
        ),
        migrations.AlterField(
            model_name='mappingtable',
            name='target_value',
            field=models.TextField(blank=True, help_text='Plane value (state group for statuses; priority string for priorities)'),
        ),
        migrations.AlterField(
            model_name='migrationcursor',
            name='container_id',
            field=models.CharField(help_text='ClickUp list/space/task id scoping this cursor', max_length=255),
        ),
        migrations.AlterField(
            model_name='migrationcursor',
            name='entity_type',
            field=models.CharField(help_text="E.g. 'tasks', 'comments', 'relations'", max_length=50),
        ),
        migrations.AlterField(
            model_name='migrationcursor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='bytes',
            field=models.BigIntegerField(default=0, help_text='Bytes transferred (attachments only)'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='plane_id',
            field=models.CharField(blank=True, help_text='Plane pk (UUID as string)', max_length=255),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='plane_type',
            field=models.CharField(help_text="Plane model name, e.g. 'Issue', 'IssueComment'", max_length=50),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='source_id',
            field=models.CharField(help_text='ClickUp entity id', max_length=255),
        ),
        migrations.AlterField(
            model_name='migrationrecord',
            name='source_type',
            field=models.CharField(help_text="ClickUp entity type, e.g. 'task', 'comment', 'attachment'", max_length=50),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='notes',
            field=models.TextField(blank=True, help_text='Operator notes'),
        ),
        migrations.AlterField(
            model_name='migrationrun',
            name='space_ids',
            field=models.JSONField(default=list, help_text='ClickUp space IDs included in this run (empty = all)'),
        ),
    ]
